### ISSUE TITLE
getUserKarmaForSubreddit() Doesn't exist in 0.12.4

### ISSUE THREAD

**Issue by BesbesCat** [reddit/devvit#222]
Hello

I tried using getUserKarmaForSubreddit() for my app after updating to 0.12.4,

The function doesn't exist in \node_modules\@devvit\public-api\apis\reddit\RedditAPIClient.js
I tried with a clean app by doing a devvit init after making sure devvit --version returns 0.12.4 and it was the same with the following error message in VSCode:
` Property 'getUserKarmaForSubreddit' does not exist on type 'RedditAPIClient'.`

The function only exists in the Changelog and doesn't seem to have been added to docs either. I was told it was implemented [here](https://github.com/reddit/devvit/issues/190#issuecomment-3528327815) 

So Am I missing something?

Thanks

**Comment by niedzielski** [comment]
thanks for the follow-up :+1:

ah, that explains it. the team is mostly focused on @devvit/web APIs for new features and future work. I'll pass your request on to see what they say but they're a pretty small group. I'll follow-up when I know more.

we do have JSDocs for this feature and it is mentioned in the changelog (after we fixed the name you flagged). previously, we had the JSDocs integrated into search but that doesn't seem to be the case any more. I'll pass this on too!

**Comment by slowcooked99** [comment]
> Noted. I will follow the updates in the Changelog. I'd appreciate it if you let me know when this feature is available for testing once it's released.
> 
> Thanks

Hi @BesbesCat, apologies for the delayed response on this. I added `getUserKarmaFromCurrentSubreddit()` around Dec 16th, as part of this commit: https://github.com/reddit/devvit/commit/30f9b5fd3a1ce051720d4553b3a92f33eaa68018

It should now be available in both `public-api` and the `reddit` packages.
