### ISSUE TITLE
[Devvit Web] settings.get / redis / reddit plugin RPC all throw 'undefined undefined: undefined' simultaneously (empty gRPC envelope) on an uploaded mod tool

### ISSUE THREAD

**Issue by ComBba** [reddit/devvit#261]
> **2026-05-14 update — issue is no longer reproducing in our app, and one line in the original report below was wrong on my part. Closing as could-not-reproduce; details in the closing comment + a follow-up comment above.**

## Summary

Every Devvit plugin RPC call inside a request handler on an uploaded private mod-tool app threw `Error: undefined undefined: undefined`. The gRPC response envelope was `{ code: undefined, details: undefined, metadata: Map(0) }`. The failure affected `settings.get`, `redis.get/set/zRange/zAdd/hSet/hGetAll`, `reddit.getModerators`, `reddit.getNewPosts`, and the inbound side of scheduler tasks identically — i.e. the *whole* plugin/sidecar layer, not a single client.

Same symptom as #258 (custom-post submission) but on a different surface: this app never calls `submitCustomPost` / `submitPost`. The shared signature (`callErrorFromStatus` → `GenericPluginClient.X` → `GrpcWrapper.request`) suggests a single underlying gRPC transport / sidecar issue, not per-client bugs.

## Environment (when actively reproducing, 2026-05-13)

- App slug: `vibe-mod`
- App URL: <https://developers.reddit.com/apps/vibe-mod>
- Devvit CLI: `0.12.23`
- `@devvit/web` / `@devvit/server` / `@devvit/start` / `@devvit/test`: `0.12.23` (also reproduced on `0.12.21`, `0.12.22`, `0.12.24-next-2026-05-12-…`, `0.13.0-next-2026-05-12-…`)
- `hono`: `4.12.18`, `@hono/node-server`: `2.0.2` (using the canonical `serve({ fetch: app.fetch, createServer, port })` from `devvit-template-react`)
- Node: `v24.15.0`
- Test subreddit: `r/SocialSeeding` (mod-installed)
- App versions tested: `0.0.5` → `0.0.25` (over 20 builds across the diagnosis)
- Publish status: uploaded (private)

## Stack trace shape (identical across every plugin)

```
Error: undefined undefined: undefined
    at callErrorFromStatus (/srv/index.cjs:4437:21)
    at Object.onReceiveStatus (/srv/index.cjs:5118:70)
    at Object.onReceiveStatus (/srv/index.cjs:4920:140)
    at Object.onReceiveStatus (/srv/index.cjs:4886:175)
    at /srv/index.cjs:16589:74
    at process.processTicksAndRejections (node:internal/process/task_queues:84:11)
for call at
    at Client3.makeUnaryRequest (/srv/index.cjs:5088:32)
    at GrpcWrapper.request (/srv/index.cjs:136120:109)
    at GenericPluginClient.<MethodName> (/srv/index.cjs:136515:93)
    at <client>.<method> (main.js:…)
    at Array.<anonymous> (main.js:…)
{
  code: undefined,
  details: undefined,
  metadata: _Metadata { internalRepr: Map(0) {}, options: {} }
}
```

`GenericPluginClient` and `GrpcWrapper` are NOT in the npm `@devvit/protos` / `@devvit/server` packages — those externalize the proto root via `externalizeDevvitProtos.ts`. They're injected into `/srv/index.cjs` at deploy time, so this trace lives inside Reddit's runtime, not the public packages.

## Runtime state at the moment of the throw (instrumented diagnostic, 2026-05-13)

```
[vibe-mod] mod-check enter: {
  sub: 'SocialSeeding',
  user: 'DragonfruitAfraid309',
  runtime: {
    hasConfig: true,            // globalThis.devvit.config IS populated
    hasMetaProvider: true,      // globalThis.devvit.metadataProvider() works
    metaKeyCount: 15,
    metaSample: [
      'devvit-installation', 'devvit-subreddit', 'devvit-app-user',
      'devvit-context', 'devvit-user', 'devvit-user-name'
    ]
  }
}
[vibe-mod] mod check: redis.get(modlist) threw: { ... 'undefined undefined: undefined' ... }
[vibe-mod] mod check: getModerators threw: { ... 'undefined undefined: undefined' ... }
```

So the *client* side wiring (ALS, `globalThis.devvit.config`, `metadataProvider`, all 15 `devvit-*` headers) was fully populated. The failure was downstream of the client.

## Things ruled out (≈10 hours / 25 builds of investigation, 2026-05-13)

| Variable | Tested | Result |
|---|---|---|
| Hono adapter shape | hand-rolled `nodeToHonoListener` vs `serve({fetch, createServer, port})` from `@hono/node-server` | both fail identically |
| `@devvit/web` version | 0.12.21, 0.12.22 (the version whose changelog claimed the fix), 0.12.23, 0.12.24-next, 0.13.0-next | all five fail identically |
| `reddit.scope` | `"moderator"` vs default `"user"` | both fail |
| `redis: true` permission | declared vs omitted | both fail |
| Install state | `devvit uninstall` + `devvit install` | unchanged |
| Setting presence | `npx devvit settings set openaiApiKey` confirmed set | doesn't matter; `settings.get` threw before evaluating value |

## Cross-reference with other open issues

- #258 — same stack signature, different surface (`reddit.submitCustomPost`). Same gRPC class.
- #259 — `scheduler.runJob()` returns a UUID but `listJobs()` is empty and jobs never execute. We saw the cron-side equivalent: gateway dispatches the cron tick to our endpoint (we get the handler's `enter` log), and any plugin call inside the handler 500s. Probable same root cause class as #259.
- #242 — `modLog client is not working in 0.12.7`. Same plugin-layer reliability theme.

## Reproduction (when active)

vibe-mod is a small Hono server. The failure reproduced by clicking any of its moderator menu items (which call `redis.get` / `reddit.getModerators`) or by waiting one cron tick (which called `settings.get` / `redis.zRange`).

We landed a defensive workaround in [Two-Weeks-Team/vibe-mod#30](https://github.com/Two-Weeks-Team/vibe-mod/pull/30) that wraps every plugin call in try/catch with `describeErr`, falls back to the gateway-side `forUserType: "moderator"` filter for mod-check, returns honest "Devvit settings/plugin RPC is unavailable in this runtime" toasts, and keeps schedulers returning HTTP 200 so the gateway doesn't retry-spam.

## ⚠️ Retraction (2026-05-14)

The original report ended with this sentence:

> *"The compose-rule UI / forms open in this state, but the actual compile (which needs `settings.get('openaiApiKey')`) cannot run — and that's the limit of what an app-side workaround can do."*

That sentence was wrong on my part. After running the compose-rule failure through 7 rounds of speculative fixes (Two-Weeks-Team/vibe-mod#32-#38), **the actual root cause was a SELECTION-typed setting returning a string array** (`["gpt-5.4-mini"]`) that we passed straight into the OpenAI request body as `"model": ["gpt-5.4-mini"]`. OpenAI rejected that with `HTTP 400 We could not parse the JSON body of your request` — generic wording for what was really a type mismatch on a single field. Postmortem with full evidence trail: [docs/postmortems/2026-05-14-openai-400-selection-array.md](https://github.com/Two-Weeks-Team/vibe-mod/blob/main/docs/postmortems/2026-05-14-openai-400-selection-array.md).

So the OpenAI 400 was conflated with the plugin-RPC issue in the original report. The plugin-RPC issue itself (the `undefined undefined: undefined` envelope across multiple plugins simultaneously) is a real thing we saw and reproduced on 2026-05-13 — but the compile failure on the failing builds was unrelated to it.

## Closing (2026-05-14)

Plugin RPC (`settings.get`, `redis.get/set/zRange`, `reddit.getModerators`) has been returning successfully in our app for the past 24+ hours of cron ticks and menu clicks. I can't tell from outside whether (a) the underlying gRPC sidecar issue was silently fixed, (b) the bug is intermittent and we're currently in a "good" window, or (c) some unrelated configuration changed.

Closing as could-not-reproduce in current state. Happy to reopen with fresh `npx devvit logs` snapshots if it returns. Linking to #258 / #259 / #242 for the broader gRPC reliability theme so anyone hitting the same `undefined undefined: undefined` envelope can find this.

**Comment by ComBba** [comment]
## 2026-05-14 follow-up

Two updates after a week of further investigation, in case it helps the team triage this:

### 1. Plugin RPC has been stable in our app for the past 24+ hours

After [Two-Weeks-Team/vibe-mod#30](https://github.com/Two-Weeks-Team/vibe-mod/pull/30) (resilient-fallback) shipped, we kept watching the logs. Across the last several deploys (v0.0.32 → v0.0.41) and many cron ticks + menu clicks, **`settings.get` / `redis.get/set/zRange` / `reddit.getModerators` have all been returning successfully** with no `undefined undefined: undefined` envelopes. Concretely, today's logs look like this:

```
[vibe-mod] scheduler/rate-limit: settings.get OK, maxPerHour= 100
[vibe-mod] mod check: getModerators → 2 mods: DragonfruitAfraid309,vibe-mod
[vibe-mod] callOpenAI: settings.get(openaiApiKey) ok: { defined: 'string', len: 164 }
```

I can't tell from outside whether (a) the underlying gRPC sidecar issue was silently fixed on Reddit's side, (b) the bug is intermittent and we're currently in a "good" window, or (c) some unrelated configuration on the app changed. But on our app, **the original symptom is no longer reproducing**.

### 2. The "compose-rule cannot run" line in the original report was wrong on my part

The original report said:

> *"the compose-rule UI / forms open in this state, but the actual compile (which needs `settings.get('openaiApiKey')`) cannot run"*

That sentence implied the menu's compile failure was caused by this plugin-RPC issue. After running it through 7 rounds of speculative fixes, **the actual root cause was a SELECTION-typed setting returning a string array** (`["gpt-5.4-mini"]`) that we passed straight into the OpenAI request body as `"model": ["gpt-5.4-mini"]`. OpenAI rejected that with `HTTP 400 We could not parse the JSON body of your request` — generic wording for what was really a type mismatch on a single field. Postmortem with full evidence trail: [docs/postmortems/2026-05-14-openai-400-selection-array.md](https://github.com/Two-Weeks-Team/vibe-mod/blob/main/docs/postmortems/2026-05-14-openai-400-selection-array.md).

So that part of the original report was conflating two unrelated bugs. The plugin-RPC issue itself (the `undefined undefined: undefined` envelope across multiple plugins simultaneously) is a real thing we saw and reproduced — but it isn't what was preventing the compile in the failing builds.

### Recommendation

Up to the team whether to keep this open as a documented platform bug worth investigating, or close as "could not reproduce in current state." Happy to run additional instrumented builds if helpful, or to attach further `npx devvit logs` snapshots from the period when the bug was actively reproducing.

**Comment by ComBba** [comment]
Could not reproduce in current state — full retraction + recovery context now in the issue body. Will reopen with fresh logs if the symptom returns.
